artifacts_root: artifacts  # Tüm çıktıların saklanacağı ana klasör

data_ingestion:  # Veri Alımı Aşaması
  root_dir: artifacts/data_ingestion  # Veri alımı için ana dizin
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip # Verinin indirileceği URL
  local_data_file: artifacts/data_ingestion/data.zip  # İndirilen veri dosyasının saklanacağı yol
  unzip_dir: artifacts/data_ingestion  # Zip dosyasının açılacağı dizin

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILE: ["train", "test","validation"]
  